first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = 'first_app'

urlpatterns = [
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^register/$',views.register,name='register'),
    url(r'^other/$',views.other,name='other'),
    url(r'^$',views.index,name='index'),
    url(r'^user_login/$',views.user_login,name='user_login')
]

first_project/first_project/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from first_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^first_app/',include('first_app.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^formpage/',views.form_name_view,name='form_name'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special'),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    #additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.username

class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

first_project/first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')





def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name needs to starts with Z")

class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter email again: ')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False,
                                 widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("Ensure Emails match")

first_project/first_app/views.py
from django.shortcuts import render
from . import forms
from django.http import HttpResponse
from first_app.models import Topic,Webpage,AccessRecord
from first_app.forms import UserForm,UserProfileInfoForm

#imports needed for the Login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required




# Create your views here.

def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpages_list}
    context_dict = {'text':'hello world','number':100}
    return render(request,'first_app/index.html',context_dict)


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'first_app/registration.html',
                            {'user_form':user_form,
                              'profile_form':profile_form,
                              'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not active")

        else:
            print("Login failure")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details")

    else:
        return render(request,'first_app/login.html',{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("Logged in, nice!")



def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("Validation Success!")
            print("Name: "+form.cleaned_data['name'])
            print("Email: "+form.cleaned_data['email'])
            print("Text: "+form.cleaned_data['text'])


    return render(request,'first_app/form_page.html',{'form':form})

def other(request):
    return render(request,'first_app/other.html')

def relative(request):
    return render(request,'first_app/relative_url_template.html')

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index'%}">ADMIN</a></li>
          <li><a class="navbar-link" href="{% url 'first_app:other'%}">OTHER</a></li>
          <li><a class="navbar-link" href="{% url 'first_app:register'%}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li> <a class='navbar-link' href="{% url 'first_app:user_login'%}">Login</a> </li>
          {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}

      <p>HERE SHOULD BE EXCLUDE</p>

      {% endblock %}

    </div>
  </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Forms</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <h1>Fill out form</h1>
    <div class="container">
      <form method="post">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>



    </div>

  </body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% load staticfiles %}
{% load my_extras %}
  {% block body_block %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>

    {{text|mycut:'hel'}}
    {{number|add:'99'}}

    <div class="container">
      <div class="jumbotron">
        <h1>Welcome to Level 2</h1>
        <h2>Here's access records:</h2>
      </div>
    </div>


<div class="djangotwo">
  {% if access_records %}
    <table>
      <thead>
        <th>Site Name</th>
        <th>Date Accessed</th>
      </thead>

      {% for acc in access_records %}
      <tr>
        <td>{{ acc.name }}</td>
        <td>{{ acc.date }}</td>
      </tr>
      {% endfor %}
    </table>
    {% else %}
      <p>NO ACCESS RECORDS FOUND</p>
    {% endif %}

</div>


  </body>
</html>

  {% endblock %}

first_project/templates/first_app/login.html
{% extends 'first_app/base.html'%}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'first_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>

</div>




{% endblock %}

first_project/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
  {% block body_block %}

    <html>
      <head>
        <meta charset="utf-8">
        <title>OTHER PAGE</title>
      </head>
      <body>
        <h1>Other page</h1>
        <a href="{% url 'first_app:relative' %}">Relative page link</a>
        <a href="{% url 'admin:index' %}">Admin Page</a>
        <a href="{% url 'index'%}">Index Page</a>
      </body>
    </html>

  {% endblock %}

first_project/templates/first_app/registration.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thanks for registering</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill up form:</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">

    </form>


  {% endif %}

</div>


{% endblock %}

first_project/templates/first_app/relative_url_template.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Relative URL page</title>
  </head>
  <body>
    <h1>Relative URL page</h1>
    <a href=""></a>
  </body>
</html>